sudo: required
dist: trusty

language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

os:
  - osx
  - windows
  - linux

install:
  - nvm install 10
  - yarn add electron-builder@next
  - yarn install

script:
  - yarn run build:electron:all
