version: "3"


services:
# TODO: prod/dev versions
#  nginx:
#    image: nginx
#    volumes:
#      - ./etc/nginx/default.template:/etc/nginx/conf.d/default.template
#    ports:
#      - "80:80"     # http
#      - "443:443"   # https
#      - "8080:8080" # webpack-dev-server :8080/sockjs-node/info
#    networks:
#      - p1devnet

  oauth2-server:
    build: .
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
    networks:
      - p1devnet
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - OAUTH2_PORT=${OAUTH2_PORT}
      - NAMESPACE=${NAMESPACE}
      - ISSUER=${ISSUER}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - POSTMESSAGE_TEMPLATE=${POSTMESSAGE_TEMPLATE}
      - POSTMESSAGE_TARGET_ORIGIN=${POSTMESSAGE_TARGET_ORIGIN}
      - REDIRECT_URL=${REDIRECT_URL}
      - SCOPES=${SCOPES}
      - CORS_ROUTES=${CORS_ROUTES}
      - CORS_VALID_ORIGIN=${CORS_VALID_ORIGIN}
      - SESSION_NAME=${SESSION_NAME}
      - SESSION_KEY=${SESSION_KEY}
      - SESSION_AGE=${SESSION_AGE}
      - API_URL=${API_URL}

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - p1devnet


networks:
  p1devnet:


volumes:
  redis-data:
  node-modules:
